[package]
name = "slquickemu"
version = "0.1.0"
authors = ["HC <hc900@hackerlan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.7"
clap = "2"
serde = { version = "1.0", features = ["derive"] }